### ISSUE TITLE
autoload

### ISSUE THREAD

**Issue by SingularisArt** [wincent/wincent#121]
This isn't a bug. It's just a question.

I'm kind of new to lua and all of that.
Could you please explain to me why you put:

```lua
return wincent.autoload('wincent.vim')
```

Could you please be detailed in your responses? I do know basic Lua, but not advanced level like this neovim config.

**Comment by wincent** [comment]
I don't know if I can provide a very good explanation for it, but the basic idea is described here:

https://github.com/wincent/wincent/blob/c298fa7d79879ff715106a136841b7c02352036c/aspects/nvim/files/.config/nvim/lua/wincent/autoload.lua#L1-L23

The "normal/idiomatic" Lua way to do this kind of thing would be to not have autoloading at all. Any time you need anything you would write `require'something'`, and if you need to use it multiple times, you write out the `require` multiple times — because modules are cached, these subsequent calls don't re-evaluate the module; they just return the already-loaded module.

The specific line you cite was added in f53783e76, which says:

> **refactor(nvim): streamline global access**
>
> Yes, globals are evil, but it is 2 AM and I reserve the right to exercise poor judgment at this time of night.
>
> Seriously though, I think the streamlining here makes for some real usability benefits (for example, see the improvement we get from doing `v:lua.wincent.something.blah()` as opposed to `luaeval("require'wincent.something'.blah()")`; the quoting becomes dramatically simpler and less error prone), so I think it's worth it.

As you can see in that commit, this allowed me to remove a bunch of `require'wincent'` calls and then just directly access "autoloaded" functions by chaining them off the `wincent` global (eg. `wincent.vim.setlocal`).

Overall I would describe all this as a "cute hack", but not necessarily a pattern I have seen anywhere else or would actively recommend. It might be a bit too magical to be a good idea. Does that answer your question, @SingularisArt?

**Comment by SingularisArt** [comment]
@wincent

Yes. Thank you.

Also, I've learned a ton from your youtube videos and I was wondering if you could create a youtube video talking about your neovim setup and how you configure your things. Like, the structure of the config and describe what each file/folder is doing.

**Comment by SingularisArt** [comment]
Quick question regarding the usage of this function. I have all of my plugin configuration located at `lua/SingularisArt/plugins` and I have a ton of files in there. How can I use this function to require all of the files in that directory?

My `init.lua` in the `lua/SingularisArt/plugins` directory is where I add my plugins using `packer`. I tried to add this at the end of my `init.lua` file:

```lua
return SingularisArt.autoload('SingularisArt.plugins')
```

You can view it [here](http://github.com/SingularisArt/Death.NeoVim).
Thanks for your help and your time!

**Comment by wincent** [comment]
[What you've got in there right now](https://github.com/SingularisArt/Death.NeoVim/blob/ae96e1bbba1be8e767805b6ff9564aa2d48c5b72/lua/SingularisArt/init.lua) looks about right to me — is it working?

**Comment by SingularisArt** [comment]
Finally, I got it to work. I just had some problems with another file.

Thanks so much!
