### ISSUE TITLE
zsh prompt looks weird

### ISSUE THREAD

**Issue by SingularisArt** [wincent/wincent#129]
## Expected Behavior

I expect the prompt to look like the prompt displayed in the README.md.

## Actual Behavior

Here's how my prompt looks like:

![Screenshot_2022-08-12_14-27-57](https://user-images.githubusercontent.com/57925294/184447272-0c8c97a4-1142-4d58-9ce6-598666610162.png)

Everything else works fine though. The time, the git status, and the location work fine. But, for some reason, there are multiple arrows being displayed and I don't have multiple zsh, bash, or whatever instances open. You can look at my zsh config [here](https://github.com/SingularisArt/Singularis/tree/master/config/dotfiles/files/zsh) and my .zshrc [here](https://github.com/SingularisArt/Singularis/blob/master/config/dotfiles/files/.zshrc). It isn't that big.

## Steps to Reproduce the Problem

1. Download my .zshrc file [here](https://raw.githubusercontent.com/SingularisArt/Singularis/master/config/dotfiles/files/.zshrc) and my zsh folder [here](https://download-directory.github.io/?url=https%3A%2F%2Fgithub.com%2FSingularisArt%2FSingularis%2Ftree%2Fmaster%2Fconfig%2Fdotfiles%2Ffiles%2Fzsh)
3. Move the .zshrc file to your home directory and the zsh folder to the .config directory
4. Close and re-open zsh
5. Let zsh download all the plugins and completions

## Specifications

- Version:5.18.16-zen1-1-zen
- Platform: Arch Linux
- Subsystem: Endeavour OS

**Comment by wincent** [comment]
This is kind of expected because of the way different environments end up acquiring a new/deeper `SHLVL`. You can see _some_ special handling in here that is intended to detect whether you're inside tmux (which would artificially inflate the `SHLVL`), or inside X (which could inflate it even more). I myself use Arch and it works for me there, but this is all very sensitive to local set-up, so I would think that the best solution for you would be to tweak the values in here to make it do the right thing:

https://github.com/wincent/wincent/blob/84bbf3590edb41ffeb8b27b18efe68c64f04a6ec/aspects/dotfiles/files/.zshrc#L163-L174

I myself have to do a bit of tweaking[^lazy], because the current config works for me on my Arch machine and on macOS, but it doesn't work on the Debian machines I SSH into at work... There might be a more elegant way of having it adapt automatically, but I am not sure what that would be... if I think of anything I'll let you know.

In any case, for the record, this is what I see for `$SHLVL` in various places:

- macOS:
  - New terminal window: 1
  - Inside a tmux session: 2
- Arch:
  - At virtual console: 1
  - New terminal window: 3
  - Inside a tmux session: 2
  - `ssh`-ed into Arch from the outside: 1
  - `ssh-`ed in, then into a tmux session: 2
- Debian:
  - `ssh`-ed in from the outside: 1
  - `ssh`-ed in, then into a tmux session: 2

[^lazy]: I've just been too lazy to do so, so far. I believe it's because my `$TERM` on those machines is set to `xterm-256color`, so my `$TMUXING` variable in the above snippet isn't getting set up.

**Comment by SingularisArt** [comment]
Thanks. Here's the new code that I use now:

```bash
  # Check for tmux by looking at $TERM, because $TMUX won't be propagated to any
  # nested sudo shells but $TERM will.
  local TMUXING=$([[ "$TERM" =~ "tmux" ]] && echo tmux)
  local INTMUX=""
  if [ -n "$TMUXING" -a -n "$TMUX" ]; then
    # In a tmux session created in a non-root or root shell.
    INTMUX='tmux'
  fi

  # Either in a root shell created inside a non-root tmux session,
  # or not in a tmux session.
  local LVL=$SHLVL
  local LVL="$(($(pstree -s $$ | grep -wo 'zsh' | wc -l)-1))"
  local SUFFIX='%(!.%F{yellow}%n%f.)%(!.%F{yellow}.%F{red})'$(printf '\u276f%.0s' {1..$LVL})'%f'

  export PS1="%F{green}${SSH_TTY:+%n@%m}%f%B${SSH_TTY:+:}%b%F{blue}%B%1~%b%F{yellow}%B%(1j.*.)%(?..!)%b%f %B%F{blue}${INTMUX}%f${SUFFIX}%b "
```

Now, here's what my zsh prompt looks like:

![Screenshot_2022-08-17_16-38-38](https://user-images.githubusercontent.com/57925294/185262016-4295be99-96f1-483f-bcfe-f880148851fd.png)
