### ISSUE TITLE
error while running a full install. netcat has no installation candidate

### ISSUE THREAD

**Issue by chrismartain** [wincent/wincent#138]
@wincent running s full install and running into an issue regarding netcat install. After looking into it, apparently there are 2 versions fo netcats: netcat-tradiional and netcat-openbsd and one should specify which one to install. 
the error message simply says: netcat has no installation candidate.

**Comment by wincent** [comment]
What OS and version is this on @chrismartain? Is it Arch?

**Comment by chrismartain** [comment]
Not running Arch, I am running Kali 6.0.0 but I also tested it Ubuntu and had a similar error. Was it only supposed to run on Arch?

**Comment by wincent** [comment]
Under [Platform status](https://github.com/wincent/wincent#platform-status), I'm using it on macOS (daily driver), Debian-ish Linux (Codespaces environment at work), Arch (Linux play desktop). So only those get tested. Additionally, due to the fact that I rarely get a new machine, it's not that often that I test a from-scratch run on a pristine install — it's usually just incremental runs to keep things up to date. As such, there are a lot of ways for entropy to creep in and break things.

**Comment by wincent** [comment]
Closing some old stale issues.
