### ISSUE TITLE
Trouble with tmux-256color when ssh'ing into remote hosts.

### ISSUE THREAD

**Issue by codybuell** [wincent/wincent#21]
Any suggestions for how to workaround having an unrecognized terminal when ssh'ing into remote hosts?  General consensus seems to be to copy and compile terminfo files on the remote host or setup an ssh alias along the lines of 'TERM=screen ssh'.  Wondering if you have come upon any other options with your setup.

**Comment by wincent** [comment]
In my case i use Ansible to set up the terminfo files on the host; works easily because I generally only work on one or three hosts.

Your other option would be a host-specific override. You could set something more conservative as a default (screen, screen-256color) and override it on specific hosts. For example I have both Vim and Zsh override files per host. Haven't needed one for tmux so far but there'd be some way to set up a symlink or something easily enough.

**Comment by codybuell** [comment]
Thanks Greg, will take a look at host-specific overrides.
