### ISSUE TITLE
Problem with Task : ssh

### ISSUE THREAD

**Issue by mehmetcanbudak** [wincent/wincent#54]
<img width="1680" alt="screen shot 2017-11-07 at 2 08 51 pm" src="https://user-images.githubusercontent.com/18473037/32512770-2388c4ee-c3c6-11e7-8ca8-2d1b15219ba7.png">

**Comment by wincent** [comment]
Yeah, you'll want to skip that task, or provide your own ssh config file at `roles/ssh/files/ssh_config` (you could even just create a blank file there if you don't want a config).

The reason is that the file contains sensitive information, [so its encrypted](https://github.com/wincent/wincent/blob/master/roles/ssh/files/.ssh_config.encrypted). I think I should tweak things so that we don't blow up if it is missing and instead just print a warning.
