### ISSUE TITLE
Have you seen CoC?

### ISSUE THREAD

**Issue by kutsan** [wincent/wincent#71]
Hi Greg! Have you seen https://github.com/neoclide/coc.nvim? I think it's better than deoplete in every aspect. I just wonder your opinion about them because looks like you still use deoplete.

**Comment by kutsan** [comment]
I believe your custom completers about your snippets? If it's so, coc has its [own snippet engine](https://github.com/neoclide/coc-snippets) that supports UltiSnips syntax without installing UltiSnips plugin. This is a big plus for me because there shouldn't be any conflict between snippet plugins whatsoever.

I used to use deoplete but generally what I like about coc is; it works out of the box, it seems fast, and supports language extensions since you don't need to deal with language servers.

**Comment by wincent** [comment]
> I believe your custom completers about your snippets? 

I do have a bunch of UltiSnips snippets, but the completers — sources actually — I'm thinking of are [in this directory](https://github.com/wincent/wincent/tree/30666bfcc9c5ee7ebce702465d27ddbc9e0e97e2/roles/vim/files/.vim/rplugin/python3/deoplete/sources); specifically, one for completing links to wiki articles when editing Markdown files in my website repo, and one for completing email addresses while editing Mutt emails. So migrating is likely to be a bit costly (I already migrated once, from YCM), so I'm pretty conservative about switching.

**Comment by taigacute** [comment]
@wincent   
 coc is very friendly to neovim's floatwindow support, coc supports lsp, so its experience is based on the language server, if the language server is done very well you will feel how good the coc is, and transplanted a big Some of the features that vscode has, coc has a lot of extensions that can reduce a lot of plugins, and most importantly, coc is faster than deoplete.

**Comment by wincent** [comment]
Yeah. LSP is great. I'm using LanguageClient-neovim for that.

I have tried out CoC but didn't notice any speed improvement over deoplete, so it didn't seem worth the switch; the one time I did [see a regression in deoplete performance](https://github.com/Shougo/deoplete.nvim/issues/900), it was rapidly fixed. I'd love to hear more about your speed claim though. If it really were provably faster I'd consider switching, even though I already have an investment in custom deoplete completers like I commented earlier.

Seems there are [other ways](https://github.com/Shougo/deoplete.nvim/issues/959) to get the floating window preview. For now I've been using the standard preview in Vim but I might try it out 

I have a colleague at work who tried CoC a bit more seriously than I did (I just tried it for a few minutes, he tried it for a few days); he ended up switching to deoplete + LanguageClient-neovim because apparently he was seeing issues with the background processes launched by CoC (too many of them).

On the balance, my preference is to keep something that works well (because I rely on this set-up) than be an early adopter of an interesting but fast-changing upstart. I'm not ruling out switching to CoC in the future though; just saying that I want to wait until the advantage it compelling.

**Comment by taigacute** [comment]
@wincent   thanks for your replay . 
I have used deoplete + LanguageClient-neovim too, and there are too many problems with their cooperation. At present, I have seen a lot of things. The author of coc used to use  LanguageClient-neovim for a while, and was very disappointed with its performance, so he made coc. Coc support for lsp is more complete, all lsp features coc are supported. more importantly. The patch for the completed floating window is provided by the coc author, so I believe that the coc support will be better. Regarding speed, I write more about golang, golang does not have a good languageserver, but if you write js, I believe that coc-tsserver will bring you a better experience. I am not familiar with other languages, so I can't evaluate them and the performance of coc.

**Comment by wincent** [comment]
The corresponding support for the floating window was added to LanguageClient-neovim in https://github.com/autozimu/LanguageClient-neovim/commit/53ce2fee7d24dd9262ea783908e2edebc71635dc

**Comment by wincent** [comment]
Probably not going to take any action on this at this time. Some context: https://youtu.be/8PZZkIr5Dcc
