### ISSUE TITLE
Statusline: double // when opening a file in ~

### ISSUE THREAD

**Issue by Konstruktionist** [wincent/wincent#72]
I've used your technique for showing filepath and filename in statusline

It used to be:
```
" Make sure we show $HOME as ~.
return substitute(l:basename . '/', '\C^' . $HOME, '~', '')
```

and I noticed that you changed it to:
```
return fnamemodify(l:basename, ':~:.') . '/'
```
commit: f6a83f105801e0fda9a737ddc7793d8739f27365

However when I tried this out and opened a file in `$HOME` my statusline says
`~//somefile.md`  
With the old `substitute` line the result is `~/somefile.md`  
In other directories I don't get double slashes.

I've only used this bit [statusline:L10-L18][1] and can't find if you are doing something anywhere else to prevent the double slahses. I'm a newbie at vimscript and your stuff is quite overwhelming at times, so I may have missed something. I looked around in `:h fnamemodify()` & `h: filename-modifiers` but don't see a solution there either.

[1]: https://github.com/wincent/wincent/blob/master/roles/dotfiles/files/.vim/autoload/wincent/statusline.vim#L10-L18

**Comment by wincent** [comment]
Thanks for reporting this. I can repro the issue, so will see if I can find a fix. If I can't, I'll just put it back the way it was (I only switched to `fnamemodify` because I thought I was re-inventing a wheel that probably didn't need to be reinvented, but if I can't make it work then I'll need to reevaluate).
